### ISSUE TITLE
Dagana integration

### ISSUE THREAD

**Issue by lucarossini-iit** [ADVRHumanoids/modular_hhcm#4]
Configuration for gripper adapter

```
joint_gripper_adapter:
        names: [dagana_2]
        thread: rt_main
        params:
            dagana_2/joint_name: {value: dagana_2_claw_joint, type: string}
            dagana_2/joint_type: {value: joint_ec, type: string}
            dagana_2/qopen: {value: -0.4, type: double}
            dagana_2/qclosed: {value: 0.6, type: double}
            dagana_2/vmax: {value: 1.0, type: double}
            dagana_2/stiffness: {value: 50.0, type: double}
```

**Comment by EdoardoRomiti** [comment]
This is now handled with the discovery and added to the _ec_all.yaml_  config file:
```yaml
joint_gripper_adapter:
        names:
            - dagana_E
        thread: rt_main
        params:
            dagana_E/joint_type:
                type: string
                value: joint_ec
            dagana_E/qclosed:
                type: double
                value: 0.6
            dagana_E/qopen:
                type: double
                value: -0.4
            dagana_E/stiffness:
                type: double
                value: 50.0
            dagana_E/vmax:
                type: double
                value: 1.0
            dagana_E/joint_name:
                type: string
                value: dagana_E_claw_joint
```
Anyway with this in the config xbot2 threads are not able to start:
```
[warn][rt_main] xbc thread 'rt_main' has not transited to run state yet 
[warn][nrt_main] xbc thread 'nrt_main' has not transited to run state yet 
```
By removing the 'joint_gripper_adapter', xbotcore starts without issues. Do we need some additional packages @alaurenzi ?
