### ISSUE TITLE
Custom resource package not discovered

### ISSUE THREAD

**Issue by FraunhoferItalia** [ADVRHumanoids/modular_hhcm#5]
Hi,

I have created a [custom resource package](https://github.com/FraunhoferItalia/fhi_resources) to collect all the fhi pino resources.
The package is inside a catkin_ws that is present in ROS_PACKAGE_PATH variable.

I modified the `config_file.yaml` in the following way:
```yaml
data_path: 'modular_data'
resources_path: 'modular_resources'
external_resources:
# the path to external resources must be absolute, even if by using variables (~, etc.)
  concert_resources_path: '$(rospack find concert_resources)'
  dagana_path: '$(rospack find dagana_urdf)'
  fhi_resources_path: '$(rospack find fhi_resources)'
  # whatever_resources_path: None
modularbot_path: 'modular_data/ModularBot'
deploy_dir: '~/src/fhi_ws/src'
```

Unfortunately I am still not able to find the modules in the gui.

_Note: this hotfix in the code allow me to visualize fhi_resources correcly_
![MicrosoftTeams-image (14)](https://github.com/ADVRHumanoids/modular_hhcm/assets/24476900/f04915fe-a338-4d80-b3be-bd72e484a585)
